import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER

NOTICES_FOLDER = "notices"

def generate_dmca_notice(owner_name, stolen_url, original_filename, watermark_id, detection_id):
    output_filename = f"stampit_dmca_{detection_id}.pdf"
    output_path = os.path.join(NOTICES_FOLDER, output_filename)

    doc = SimpleDocTemplate(output_path, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    today = datetime.now().strftime("%B %d, %Y")

    title_style = ParagraphStyle("T", parent=styles["Title"], fontSize=16,
                                  spaceAfter=20, alignment=TA_CENTER)
    heading_style = ParagraphStyle("H", parent=styles["Heading2"], fontSize=12,
                                    spaceAfter=6, spaceBefore=12)
    body_style = ParagraphStyle("B", parent=styles["Normal"], fontSize=10,
                                 spaceAfter=8, leading=14)
    footer_style = ParagraphStyle("F", parent=styles["Normal"], fontSize=8,
                                   textColor=(0.5, 0.5, 0.5), alignment=TA_CENTER)

    story = [
        Paragraph("DMCA TAKEDOWN NOTICE", title_style),
        Paragraph("Digital Millennium Copyright Act — Section 512(c)", body_style),
        Paragraph("Generated by StampIt — Digital Asset Protection Platform", body_style),
        Spacer(1, 0.4*cm),
        Paragraph(f"Date: {today}", body_style),
        Paragraph("1. CLAIMANT", heading_style),
        Paragraph(f"Copyright Owner: <b>{owner_name}</b>", body_style),
        Paragraph(f"Platform: StampIt (stampit.io)", body_style),
        Paragraph(f"Content Fingerprint ID: {watermark_id}", body_style),
        Paragraph("2. INFRINGING CONTENT", heading_style),
        Paragraph(f"Infringing URL: <b>{stolen_url}</b>", body_style),
        Paragraph("3. ORIGINAL CONTENT", heading_style),
        Paragraph(f"Original File: {original_filename}", body_style),
        Paragraph(f"Watermark ID: {watermark_id} (invisibly embedded in original video)", body_style),
        Paragraph("4. GOOD FAITH STATEMENT", heading_style),
        Paragraph("I have a good faith belief that the use of this material is not authorized "
                  "by the copyright owner, its agent, or the law.", body_style),
        Paragraph("5. REQUESTED ACTION", heading_style),
        Paragraph("Please immediately remove or disable access to the infringing material.", body_style),
        Spacer(1, 1*cm),
        Paragraph("_" * 40, body_style),
        Paragraph(f"Signed: {owner_name}", body_style),
        Paragraph(f"Date: {today}", body_style),
        Spacer(1, 0.5*cm),
        Paragraph("Auto-generated by StampIt — stampit.io", footer_style)
    ]

    doc.build(story)
    return output_path, output_filename
